name: Build & Deploy Backend

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm install
      - run: npm run build --if-present
      - run: npm run dev --if-present

      - name: Archive files
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            backend_inventario/
            captain-definition
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
          args: |
            --build-arg DB_USER=${{ secrets.DB_USER }}
            --build-arg DB_HOST=${{ secrets.DB_HOST }}
            --build-arg DB_NAME=${{ secrets.DB_NAME }}
            --build-arg DB_PASS=${{ secrets.DB_PASS }}
            --build-arg DB_PORT=${{ secrets.DB_PORT }}
            --build-arg NODE_PORT=${{ secrets.NODE_PORT }}
            --build-arg ORIGIN=${{ secrets.ORIGIN }}
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }}
